// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SneakerStoreAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250623224953_ReseedSneakers")]
    partial class ReseedSneakers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SneakerStoreAPI.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SneakerId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SneakerId");

                    b.HasIndex("UserId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("SneakerStoreAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SneakerStoreAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SneakerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("SneakerId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SneakerStoreAPI.Models.Sneaker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Sneakers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Jordan",
                            ImageUrl = "https://cdn.flightclub.com/TEMPLATE/307016/1.jpg?w=1920",
                            Name = "Air Jordan 1",
                            Price = 300m
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Nike",
                            ImageUrl = "https://cdn.flightclub.com/TEMPLATE/253215/1.jpg?w=1920",
                            Name = "Nike Dunk Low",
                            Price = 120m
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Adidas",
                            ImageUrl = "https://cdn.flightclub.com/TEMPLATE/368573/1.jpg?w=1920",
                            Name = "Yeezy Boost 350",
                            Price = 200m
                        },
                        new
                        {
                            Id = 4,
                            Brand = "New Balance",
                            ImageUrl = "https://cdn.flightclub.com/TEMPLATE/371711/1.jpg?w=1920",
                            Name = "New Balance 550",
                            Price = 110m
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Adidas",
                            ImageUrl = "https://cdn.flightclub.com/TEMPLATE/460574/1.jpg?w=1920",
                            Name = "Adidas Samba OG",
                            Price = 90m
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Puma",
                            ImageUrl = "https://cdn.flightclub.com/TEMPLATE/397161/1.jpg?w=1920",
                            Name = "Puma RS-X",
                            Price = 100m
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Converse",
                            ImageUrl = "https://cdn.flightclub.com/TEMPLATE/301688/1.jpg?w=1920",
                            Name = "Converse Chuck 70",
                            Price = 75m
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Reebok",
                            ImageUrl = "https://cdn.flightclub.com/TEMPLATE/363222/1.jpg?w=1920",
                            Name = "Reebok Club C 85",
                            Price = 85m
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Asics",
                            ImageUrl = "https://cdn.flightclub.com/TEMPLATE/389891/1.jpg?w=1920",
                            Name = "Asics Gel-Lyte III",
                            Price = 95m
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Vans",
                            ImageUrl = "https://cdn.flightclub.com/TEMPLATE/350502/1.jpg?w=1920",
                            Name = "Vans Old Skool",
                            Price = 70m
                        },
                        new
                        {
                            Id = 12,
                            Brand = "New Balance",
                            ImageUrl = "https://cdn.flightclub.com/TEMPLATE/350162/1.jpg?w=1920",
                            Name = "New Balance 2002R",
                            Price = 160m
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Jordan",
                            ImageUrl = "https://cdn.flightclub.com/TEMPLATE/011502/1.jpg?w=1920",
                            Name = "Retro Cement 3",
                            Price = 300m
                        });
                });

            modelBuilder.Entity("SneakerStoreAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SneakerStoreAPI.Models.CartItem", b =>
                {
                    b.HasOne("SneakerStoreAPI.Models.Sneaker", "Sneaker")
                        .WithMany()
                        .HasForeignKey("SneakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SneakerStoreAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sneaker");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SneakerStoreAPI.Models.Order", b =>
                {
                    b.HasOne("SneakerStoreAPI.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SneakerStoreAPI.Models.OrderItem", b =>
                {
                    b.HasOne("SneakerStoreAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SneakerStoreAPI.Models.Sneaker", "Sneaker")
                        .WithMany()
                        .HasForeignKey("SneakerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Sneaker");
                });

            modelBuilder.Entity("SneakerStoreAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SneakerStoreAPI.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
